<a href="https://colab.research.google.com/github/shammika000/sri-lanka-electricity-demand-forecasting/blob/main/ml/notebooks/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/load_forecasting_dataset_corrected.csv')
df.head()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW)
0,1/1/2020 0:00,28.993428,75.011269,1.053861,4.140513,185.892561,925.621430,502.915605,20.454440,2.0,0.0,1.0,Summer,0.0,1599.342831
1,1/1/2020 0:15,27.723471,77.024015,1.085152,9.446997,281.782650,1020.823521,497.286366,27.776449,2.0,0.0,1.0,Summer,0.0,1472.347140
2,1/1/2020 0:30,29.295377,74.732958,3.363800,4.265813,328.942058,1028.847455,488.816292,21.097420,2.0,0.0,1.0,Summer,0.0,1629.537708
3,1/1/2020 0:45,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2.0,0.0,1.0,Summer,1.0,1804.605971
4,1/1/2020 1:00,27.531693,79.709858,1.366819,4.201393,205.494256,934.477462,488.565716,27.079114,2.0,1.0,1.0,Summer,0.0,1453.169325

In [ ]:
df.shape

(22777, 15)

In [ ]:
df.columns

Index(['Timestamp', 'Temperature (°C)', 'Humidity (%)', 'Wind Speed (m/s)',
       'Rainfall (mm)', 'Solar Irradiance (W/m²)', 'GDP (LKR)',
       'Per Capita Energy Use (kWh)', 'Electricity Price (LKR/kWh)',
       'Day of Week', 'Hour of Day', 'Month', 'Season', 'Public Event',
       'Load Demand (kW)'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22777 entries, 0 to 22776
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Timestamp                    22777 non-null  object
 1   Temperature (°C)             22777 non-null  float64
 2   Humidity (%)                 22777 non-null  float64
 3   Wind Speed (m/s)             22777 non-null  float64
 4   Rainfall (mm)                22777 non-null  float64
 5   Solar Irradiance (W/m²)      22777 non-null  float64
 6   GDP (LKR)                    22777 non-null  float64
 7   Per Capita Energy Use (kWh)  22776 non-null  float64
 8   Electricity Price (LKR/kWh)  22776 non-null  float64
 9   Day of Week                  22776 non-null  float64
 10  Hour of Day                  22776 non-null  float64
 11  Month                        22776 non-null  float64
 12  Season                       22776 non-null  object
 13  Public Event                 22776 non-null  float64
 14  Load Demand (kW)             22776 non-null  float64
dtypes: float64(13), object(2)
memory usage: 2.6+ MB

In [ ]:
df.describe()

,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Public Event,Load Demand (kW)
count,22777.000000,22777.000000,22777.000000,22777.000000,22777.000000,22777.000000,22776.000000,22776.000000,22776.000000,22776.000000,22776.000000,22776.00000,22776.000000
mean,28.003540,79.983833,1.994347,4.982285,249.730761,1000.344730,499.816803,24.998994,3.006322,11.490516,4.417281,0.05014,1500.362736
std,2.003959,5.018514,1.002068,5.071417,50.218260,49.936220,20.132613,5.014130,2.000034,6.925072,2.251558,0.21824,200.395928
min,20.155199,60.652155,-2.312973,0.000224,54.210364,800.427592,408.061036,6.145386,0.000000,0.000000,1.000000,0.00000,715.519950
25%,26.656753,76.625014,1.314199,1.407582,215.857006,967.004248,486.311646,21.593891,1.000000,5.000000,2.000000,0.00000,1365.692001
50%,28.003826,80.011978,1.992573,3.426770,249.353670,1000.392543,499.841517,24.992257,3.000000,11.000000,4.000000,0.00000,1500.388978
75%,29.357894,83.373100,2.670275,6.863578,283.880635,1034.348085,513.189449,28.426000,5.000000,17.000000,6.000000,0.00000,1635.799187
max,36.958168,98.910939,5.636362,52.606138,449.497275,1210.846858,592.327679,44.207808,6.000000,23.000000,8.000000,1.00000,2395.816850

In [ ]:
df.isnull().sum()

Timestamp                      0
Temperature (°C)               0
Humidity (%)                   0
Wind Speed (m/s)               0
Rainfall (mm)                  0
Solar Irradiance (W/m²)        0
GDP (LKR)                      0
Per Capita Energy Use (kWh)    1
Electricity Price (LKR/kWh)    1
Day of Week                    1
Hour of Day                    1
Month                          1
Season                         1
Public Event                   1
Load Demand (kW)               1
dtype: int64