<a href="https://colab.research.google.com/github/shammika000/sri-lanka-electricity-demand-forecasting/blob/main/ml/notebooks/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv('/content/load_forecasting_dataset_corrected.csv')
df.head()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW)
0,1/1/2020 0:00,28.993428,75.011269,1.053861,4.140513,185.892561,925.621430,502.915605,20.454440,2,0,1,Summer,0,1599.342831
1,1/1/2020 0:15,27.723471,77.024015,1.085152,9.446997,281.782650,1020.823521,497.286366,27.776449,2,0,1,Summer,0,1472.347140
2,1/1/2020 0:30,29.295377,74.732958,3.363800,4.265813,328.942058,1028.847455,488.816292,21.097420,2,0,1,Summer,0,1629.537708
3,1/1/2020 0:45,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2,0,1,Summer,1,1804.605971
4,1/1/2020 1:00,27.531693,79.709858,1.366819,4.201393,205.494256,934.477462,488.565716,27.079114,2,1,1,Summer,0,1453.169325

In [12]:
df.shape

(189888, 15)

In [13]:
df.columns

Index(['Timestamp', 'Temperature (°C)', 'Humidity (%)', 'Wind Speed (m/s)',
       'Rainfall (mm)', 'Solar Irradiance (W/m²)', 'GDP (LKR)',
       'Per Capita Energy Use (kWh)', 'Electricity Price (LKR/kWh)',
       'Day of Week', 'Hour of Day', 'Month', 'Season', 'Public Event',
       'Load Demand (kW)'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189888 entries, 0 to 189887
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Timestamp                    189888 non-null  object
 1   Temperature (°C)             189888 non-null  float64
 2   Humidity (%)                 189888 non-null  float64
 3   Wind Speed (m/s)             189888 non-null  float64
 4   Rainfall (mm)                189888 non-null  float64
 5   Solar Irradiance (W/m²)      189888 non-null  float64
 6   GDP (LKR)                    189888 non-null  float64
 7   Per Capita Energy Use (kWh)  189888 non-null  float64
 8   Electricity Price (LKR/kWh)  189888 non-null  float64
 9   Day of Week                  189888 non-null  int64
 10  Hour of Day                  189888 non-null  int64
 11  Month                        189888 non-null  int64
 12  Season                       189888 non-null  object
 13  Public Event                 189888 non-null  int64
 14  Load Demand (kW)             189888 non-null  float64
dtypes: float64(9), int64(4), object(2)
memory usage: 21.7+ MB

In [15]:
df.describe()

,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Public Event,Load Demand (kW)
count,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000,189888.000000
mean,28.001544,79.998447,1.996106,5.014217,249.938317,1000.083804,499.909985,24.998521,3.001011,11.500000,6.253286,0.049650,1500.154422
std,1.999267,5.002994,1.002337,5.016601,50.008961,50.015166,20.040060,4.998985,1.998741,6.922205,3.465723,0.217222,199.926679
min,19.068792,57.930570,-2.829436,0.000004,53.558277,779.558268,407.111625,3.268386,0.000000,0.000000,1.000000,0.000000,606.879227
25%,26.652234,76.621433,1.317979,1.435887,216.176066,966.274369,486.400599,21.623224,1.000000,5.750000,3.000000,0.000000,1365.223394
50%,28.002750,80.003040,1.995783,3.480060,249.871247,1000.001997,499.947457,25.010508,3.000000,11.500000,6.000000,0.000000,1500.274982
75%,29.350713,83.368748,2.673888,6.954906,283.683824,1033.802397,513.405061,28.376540,5.000000,17.250000,9.000000,0.000000,1635.071296
max,37.124229,101.096832,6.301848,59.219061,449.497275,1251.690264,592.327679,47.420391,6.000000,23.000000,12.000000,1.000000,2412.422945

In [16]:
df.isnull().sum()

Timestamp                      0
Temperature (°C)               0
Humidity (%)                   0
Wind Speed (m/s)               0
Rainfall (mm)                  0
Solar Irradiance (W/m²)        0
GDP (LKR)                      0
Per Capita Energy Use (kWh)    0
Electricity Price (LKR/kWh)    0
Day of Week                    0
Hour of Day                    0
Month                          0
Season                         0
Public Event                   0
Load Demand (kW)               0
dtype: int64